import { useState, useEffect } from 'react'
import { io } from 'socket.io-client'

const API_BASE = import.meta.env.VITE_API_URL || 'http://localhost:5000'

export default function HackathonLiveHub() {
  const [loading, setLoading] = useState(false)
  const [isSimulatorRunning, setIsSimulatorRunning] = useState(false)
  const [liveEvents, setLiveEvents] = useState([])
  const [emergencies, setEmergencies] = useState([])
  const [donors, setDonors] = useState([])
  const [forecast, setForecast] = useState(null)
  const [aiStatus, setAiStatus] = useState({ model: 'gemini-3.6-flash', status: 'operational' })
  const [lastRefreshed, setLastRefreshed] = useState(new Date().toLocaleTimeString())
  const [notification, setNotification] = useState(null)

  // Fetch initial live AI data
  const fetchLiveAIData = async () => {
    setLoading(true)
    try {
      const res = await fetch(`${API_BASE}/api/v1/ai/live-feed`)
      const json = await res.json()
      if (json.success && json.data) {
        setEmergencies(json.data.emergencies || [])
        setDonors(json.data.donors || [])
        setForecast(json.data.forecast || null)
        setLastRefreshed(new Date().toLocaleTimeString())
        showToast('✅ Fresh Live Data Generated by Gemini AI!')
      }
    } catch (err) {
      console.error('Failed to fetch AI live data:', err)
      showToast('⚠️ Using High-Fidelity Simulation Fallback')
    } finally {
      setLoading(false)
    }
  }

  // Check simulator status
  const checkSimulatorStatus = async () => {
    try {
      const res = await fetch(`${API_BASE}/api/v1/ai/simulator/status`)
      const json = await res.json()
      if (json.success) {
        setIsSimulatorRunning(json.isRunning)
        if (json.recentEvents && json.recentEvents.length > 0) {
          setLiveEvents(json.recentEvents)
        }
      }
    } catch (err) {
      console.warn('Could not query simulator status:', err)
    }
  }

  // Toggle background simulator
  const toggleSimulator = async () => {
    try {
      const endpoint = isSimulatorRunning ? '/api/v1/ai/simulator/stop' : '/api/v1/ai/simulator/start'
      const res = await fetch(`${API_BASE}${endpoint}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ intervalMs: 10000 })
      })
      const json = await res.json()
      if (json.success) {
        setIsSimulatorRunning(!isSimulatorRunning)
        showToast(!isSimulatorRunning ? '🚀 Live AI Event Simulator STARTED!' : '🛑 Live AI Simulator STOPPED')
      }
    } catch (err) {
      console.error('Error toggling simulator:', err)
    }
  }

  // Simulate Instant Emergency SOS
  const triggerSimulatedEmergency = async () => {
    try {
      setLoading(true)
      const res = await fetch(`${API_BASE}/api/v1/ai/simulate-emergency`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      })
      const json = await res.json()
      if (json.success) {
        showToast(`🚨 Live Emergency SOS Broadcasted: ${json.data.bloodGroup} at ${json.data.hospitalName}!`)
        setEmergencies(prev => [json.data, ...prev.slice(0, 5)])
      }
    } catch (err) {
      console.error('Error simulating emergency:', err)
    } finally {
      setLoading(false)
    }
  }

  const showToast = (msg) => {
    setNotification(msg)
    setTimeout(() => setNotification(null), 4000)
  }

  // Socket.io real-time listener for live pulses and AI events
  useEffect(() => {
    fetchLiveAIData()
    checkSimulatorStatus()

    const socket = io(API_BASE, {
      transports: ['websocket', 'polling'],
      reconnectionAttempts: 5,
    })

    socket.on('live-ai-event', (event) => {
      setLiveEvents(prev => [event, ...prev.slice(0, 19)])
      showToast(`📢 Live Event: ${event.title}`)
    })

    socket.on('live-pulse', (pulse) => {
      if (pulse.latestEvent) {
        setLiveEvents(prev => [pulse.latestEvent, ...prev.slice(0, 19)])
      }
    })

    return () => {
      socket.disconnect()
    }
  }, [])

  return (
    <div className="animate-fade-in" style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
      {/* Top Banner Alert / Notification */}
      {notification && (
        <div style={{
          background: 'linear-gradient(90deg, rgba(220, 20, 60, 0.9), rgba(139, 0, 0, 0.9))',
          color: '#fff',
          padding: '12px 20px',
          borderRadius: 12,
          fontWeight: 600,
          boxShadow: '0 8px 32px rgba(220, 20, 60, 0.3)',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
        }}>
          <span>{notification}</span>
          <button onClick={() => setNotification(null)} style={{ background: 'none', border: 'none', color: '#fff', cursor: 'pointer', fontSize: '1rem' }}>✕</button>
        </div>
      )}

      {/* Control Console */}
      <div className="glass-card" style={{
        background: 'linear-gradient(135deg, rgba(25, 25, 35, 0.75), rgba(40, 15, 25, 0.75))',
        border: '1px solid rgba(220, 20, 60, 0.3)',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.4)'
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 16 }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 4 }}>
              <h2 style={{ fontSize: '1.4rem', fontWeight: 800, margin: 0, background: 'linear-gradient(90deg, #FF6B6B, #FFD93D)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>
                ⚡ Gemini AI Live Hackathon Engine
              </h2>
              <span className="badge badge-green" style={{ fontSize: '0.75rem', textTransform: 'uppercase' }}>
                🟢 {aiStatus.model} ACTIVE
              </span>
            </div>
            <p style={{ margin: 0, fontSize: '0.85rem', color: 'var(--color-text-muted)' }}>
              Real-time generative stream generating active Indian emergencies, clinical matching rationale, and supply chain telemetry.
            </p>
          </div>

          {/* Action Buttons */}
          <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap' }}>
            <button
              onClick={fetchLiveAIData}
              disabled={loading}
              className="btn btn-secondary"
              style={{ padding: '10px 18px', fontSize: '0.85rem', fontWeight: 700 }}
            >
              {loading ? '⏳ Generating AI Feed...' : '🔄 Regenerate AI Live Feed'}
            </button>

            <button
              onClick={triggerSimulatedEmergency}
              disabled={loading}
              className="btn"
              style={{
                background: 'linear-gradient(135deg, #DC143C, #8B0000)',
                color: '#fff',
                padding: '10px 18px',
                fontSize: '0.85rem',
                fontWeight: 700,
                border: 'none',
                boxShadow: '0 4px 14px rgba(220, 20, 60, 0.4)'
              }}
            >
              🚨 Trigger Live SOS Broadcast
            </button>

            <button
              onClick={toggleSimulator}
              className="btn"
              style={{
                background: isSimulatorRunning ? 'linear-gradient(135deg, #00C853, #007E33)' : 'rgba(255,255,255,0.08)',
                color: '#fff',
                padding: '10px 18px',
                fontSize: '0.85rem',
                fontWeight: 700,
                border: isSimulatorRunning ? 'none' : '1px solid rgba(255,255,255,0.2)',
                boxShadow: isSimulatorRunning ? '0 0 20px rgba(0, 200, 83, 0.5)' : 'none'
              }}
            >
              {isSimulatorRunning ? '🟢 Live Simulator Running (ON)' : '▶ Start Real-Time Simulator'}
            </button>
          </div>
        </div>

        <div style={{ display: 'flex', gap: 24, marginTop: 18, paddingTop: 16, borderTop: '1px solid rgba(255,255,255,0.08)', fontSize: '0.8rem', color: 'var(--color-text-muted)', flexWrap: 'wrap' }}>
          <div>📡 <strong>Status:</strong> <span style={{ color: '#00E676' }}>Connected & Polling</span></div>
          <div>⏱️ <strong>Last Generated:</strong> {lastRefreshed}</div>
          <div>📍 <strong>Target Region:</strong> Pan-India Metros (Mumbai, Delhi, Bengaluru, Hyderabad, Pune)</div>
          <div>🧠 <strong>AI Triage Engine:</strong> Dual-Heuristic Geodesic + Trust Score Matrix</div>
        </div>
      </div>

      {/* Grid: 2 Columns - Live Emergencies & Shortage Forecast */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(380px, 1fr))', gap: 24 }}>
        
        {/* Section 1: Active Live Emergencies Stream */}
        <div className="glass-card">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
            <h3 style={{ fontWeight: 800, fontSize: '1.05rem', display: 'flex', alignItems: 'center', gap: 8 }}>
              <span>🚨</span> Live Emergency Blood Stream ({emergencies.length})
            </h3>
            <span className="badge badge-red" style={{ animation: 'pulse 2s infinite' }}>LIVE DISPATCH</span>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
            {emergencies.map((emg, idx) => (
              <div key={emg.id || idx} style={{
                background: 'rgba(255, 255, 255, 0.03)',
                border: '1px solid rgba(220, 20, 60, 0.25)',
                borderRadius: 12,
                padding: 14,
                display: 'flex',
                flexDirection: 'column',
                gap: 8,
              }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                  <div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                      <span style={{
                        background: 'linear-gradient(135deg, #DC143C, #8B0000)',
                        color: '#fff',
                        fontWeight: 900,
                        fontSize: '0.95rem',
                        padding: '3px 10px',
                        borderRadius: 6,
                      }}>
                        {emg.bloodGroup}
                      </span>
                      <strong style={{ fontSize: '0.95rem' }}>{emg.hospitalName}</strong>
                    </div>
                    <div style={{ fontSize: '0.78rem', color: 'var(--color-text-muted)', marginTop: 4 }}>
                      📍 {emg.location?.city || emg.location?.address || 'Metro Area'} • {emg.componentType || 'Whole Blood'} • {emg.unitsNeeded || 2} Units
                    </div>
                  </div>
                  <span className={`badge ${emg.urgencyLevel === 'critical' ? 'badge-red' : 'badge-yellow'}`}>
                    {emg.urgencyLevel?.toUpperCase() || 'HIGH'}
                  </span>
                </div>

                <div style={{ fontSize: '0.82rem', color: '#e0e0e0', background: 'rgba(0,0,0,0.25)', padding: '8px 10px', borderRadius: 8 }}>
                  🩺 <em>"{emg.patientCondition}"</em>
                </div>

                {emg.aiMatchingInsight && (
                  <div style={{ fontSize: '0.78rem', color: '#64B5F6', display: 'flex', alignItems: 'center', gap: 6 }}>
                    <span>🧠 AI Triage:</span> {emg.aiMatchingInsight}
                  </div>
                )}

                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: '0.75rem', color: 'var(--color-text-muted)', borderTop: '1px solid rgba(255,255,255,0.05)', paddingTop: 6 }}>
                  <span>Elapsed: <strong>{emg.timeElapsedMinutes || 4} min ago</strong></span>
                  <span>AI Score: <strong style={{ color: '#00E676' }}>{emg.aiPriorityScore || 96}%</strong></span>
                  <span>Matched Donors: <strong style={{ color: '#FFD93D' }}>{emg.matchedDonorsCount || 5} notified</strong></span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Section 2: AI Shortage Forecast & Demand Surge */}
        <div className="glass-card">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
            <h3 style={{ fontWeight: 800, fontSize: '1.05rem', display: 'flex', alignItems: 'center', gap: 8 }}>
              <span>🧠</span> Gemini Supply Chain & Deficit Forecast
            </h3>
            <span className="badge badge-blue">PREDICTIVE AI</span>
          </div>

          {forecast && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
              {/* Executive Summary */}
              <div style={{ background: 'rgba(41, 182, 246, 0.08)', border: '1px solid rgba(41, 182, 246, 0.25)', padding: 12, borderRadius: 10, fontSize: '0.83rem', color: '#E1F5FE', lineHeight: 1.4 }}>
                <strong>Forecast Executive Note:</strong> {forecast.summary}
              </div>

              {/* Critical Shortages */}
              <div>
                <h4 style={{ fontSize: '0.88rem', fontWeight: 700, marginBottom: 10, color: '#FF5252' }}>
                  ⚠️ Critical Deficit Warnings
                </h4>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                  {(forecast.criticalShortages || []).map((sh, idx) => (
                    <div key={idx} style={{ background: 'rgba(255,255,255,0.03)', padding: 12, borderRadius: 10, borderLeft: '4px solid #FF1744' }}>
                      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                        <strong style={{ fontSize: '0.9rem', color: '#fff' }}>
                          {sh.bloodGroup} {sh.componentType}
                        </strong>
                        <span className="badge badge-red">{sh.riskLevel?.toUpperCase()} RISK</span>
                      </div>
                      <div style={{ fontSize: '0.78rem', color: 'var(--color-text-muted)', margin: '4px 0' }}>
                        Current Stock: <strong style={{ color: '#FF5252' }}>{sh.currentStockUnits} units</strong> (Min Required: {sh.criticalThreshold}) • Projected Deficit: <strong>{sh.projectedDeficitHours}h</strong>
                      </div>
                      <div style={{ fontSize: '0.76rem', color: '#FFCDD2' }}>
                        {sh.reason}
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Seasonal Trends */}
              {forecast.seasonalTrends && forecast.seasonalTrends.length > 0 && (
                <div>
                  <h4 style={{ fontSize: '0.88rem', fontWeight: 700, marginBottom: 8, color: '#FFD93D' }}>
                    📈 Seasonal Demand Surge Factors
                  </h4>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                    {forecast.seasonalTrends.map((tr, idx) => (
                      <div key={idx} style={{ background: 'rgba(255, 217, 61, 0.05)', border: '1px solid rgba(255, 217, 61, 0.2)', padding: 10, borderRadius: 8, fontSize: '0.78rem' }}>
                        <div style={{ fontWeight: 700, color: '#FFD93D' }}>{tr.trendTitle} ({tr.impact})</div>
                        <div style={{ color: 'var(--color-text-muted)', marginTop: 2 }}>{tr.recommendation}</div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Action Plan */}
              {forecast.aiActionPlan && (
                <div style={{ background: 'rgba(0, 230, 118, 0.05)', border: '1px solid rgba(0, 230, 118, 0.2)', padding: 12, borderRadius: 10 }}>
                  <h4 style={{ fontSize: '0.85rem', fontWeight: 700, color: '#00E676', marginBottom: 6 }}>
                    🎯 Recommended Strategic Actions
                  </h4>
                  <ul style={{ margin: 0, paddingLeft: 18, fontSize: '0.78rem', color: '#C8E6C9', display: 'flex', flexDirection: 'column', gap: 4 }}>
                    {forecast.aiActionPlan.map((act, i) => (
                      <li key={i}>{act}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Section 3: Live Verified Donors Directory & Real-Time Event Ticker */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(380px, 1fr))', gap: 24 }}>
        
        {/* Live Donors Stream */}
        <div className="glass-card">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
            <h3 style={{ fontWeight: 800, fontSize: '1.05rem', display: 'flex', alignItems: 'center', gap: 8 }}>
              <span>🩸</span> Live Verified Volunteer Donors ({donors.length})
            </h3>
            <span className="badge badge-green">AADHAAR VERIFIED</span>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {donors.map((d, idx) => (
              <div key={d.id || idx} style={{
                background: 'rgba(255,255,255,0.03)',
                padding: 12,
                borderRadius: 10,
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                border: '1px solid rgba(255,255,255,0.05)'
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                  <div style={{
                    width: 38,
                    height: 38,
                    borderRadius: '50%',
                    background: 'linear-gradient(135deg, #8B0000, #DC143C)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontWeight: 800,
                    fontSize: '0.85rem'
                  }}>
                    {d.bloodGroup}
                  </div>
                  <div>
                    <div style={{ fontWeight: 700, fontSize: '0.9rem', display: 'flex', alignItems: 'center', gap: 6 }}>
                      {d.name}
                      {d.verified && <span title="Aadhaar HMAC Verified" style={{ color: '#00E676', fontSize: '0.8rem' }}>✓</span>}
                    </div>
                    <div style={{ fontSize: '0.75rem', color: 'var(--color-text-muted)' }}>
                      📍 {d.city} • {d.totalDonations} Donations • Avg Response: {d.responseTimeAvg || '3.2 min'}
                    </div>
                  </div>
                </div>

                <div style={{ textAlign: 'right' }}>
                  <div style={{ fontWeight: 800, color: '#00E676', fontSize: '0.95rem' }}>
                    {d.trustScore}<span style={{ fontSize: '0.7rem', color: 'var(--color-text-muted)' }}>/100</span>
                  </div>
                  <div style={{ fontSize: '0.7rem', color: '#FFD93D' }}>
                    {d.badge || 'Volunteer'}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Live Simulator Ticker Feed */}
        <div className="glass-card">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
            <h3 style={{ fontWeight: 800, fontSize: '1.05rem', display: 'flex', alignItems: 'center', gap: 8 }}>
              <span>📡</span> Real-Time Platform Event Stream
            </h3>
            <span className={`badge ${isSimulatorRunning ? 'badge-green' : 'badge-yellow'}`}>
              {isSimulatorRunning ? '🔴 SIMULATOR ACTIVE' : 'PAUSED'}
            </span>
          </div>

          <div style={{ maxHeight: 380, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 10, paddingRight: 4 }}>
            {liveEvents.length === 0 ? (
              <div style={{ textAlign: 'center', padding: '30px 0', color: 'var(--color-text-muted)', fontSize: '0.85rem' }}>
                <p>No real-time events captured yet.</p>
                <button onClick={toggleSimulator} className="btn btn-secondary" style={{ fontSize: '0.8rem', padding: '6px 14px' }}>
                  Start Simulator Ticker
                </button>
              </div>
            ) : (
              liveEvents.map((evt, idx) => (
                <div key={evt.eventId || idx} style={{
                  background: 'rgba(255,255,255,0.02)',
                  borderLeft: `4px solid ${evt.type === 'EMERGENCY_SOS' ? '#FF1744' : evt.type === 'DONOR_ACCEPTED' ? '#00E676' : '#29B6F6'}`,
                  padding: '10px 12px',
                  borderRadius: '0 8px 8px 0',
                }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 }}>
                    <strong style={{ fontSize: '0.82rem', color: '#fff' }}>{evt.title}</strong>
                    <span style={{ fontSize: '0.7rem', color: 'var(--color-text-muted)' }}>
                      {evt.timestamp ? new Date(evt.timestamp).toLocaleTimeString() : 'Just now'}
                    </span>
                  </div>
                  <div style={{ fontSize: '0.76rem', color: 'var(--color-text-secondary)', lineHeight: 1.3 }}>
                    {evt.description}
                  </div>
                </div>
              ))
            )}
          </div>
        </div>

      </div>
    </div>
  )
}
